### PR TITLE
Change fmt mapping and SRTP policies API

### LINKED ISSUE #24: Fix format of :new_rtp_stream notification
After #20 `SessionBin` notifies about new stream using `{:new_rtp_stream, ssrc, encoding_name}` notification. The `encoding_name` is retrived from `fmt_mappings` or registered payloads. The problem is that proper `fmt_mapping` is known after receiving SDP offer so after starting SessionBin. Thus SessionBin fails for dynamic payload types beacuse it lacks proper mapping information.

Proposed solution is to change notification to `{:new_rtp_stream, ssrc, payload_type}` and add options to `:output` pad. These options should include mapping `payload_type` => `encoding_name` (this can be implemented in a similar way to options for `:rtp_output` pad)

### PR DESCRIPTION
**Pull request by mickel8**
Closes #24 and #25

### CODE REVIEW

File: lib/membrane/srtp/encryptor.ex [hunk 1]
```diff
@@ -13,17 +13,28 @@ defmodule Membrane.SRTP.Encryptor do
...
               ]
 
   @impl true
-  def handle_init(options) do
-    {:ok, Map.from_struct(options) |> Map.merge(%{srtp: nil})}
+  def handle_init(%__MODULE__{policies: policies}) do
+    state = %{
+      policies: policies,
+      srtp: nil,
+      ready: ready?(policies),
```
Comment (mat-hek) [inline lib/membrane/srtp/encryptor.ex:28]:
```suggestion
      ready: not Enum.empty?(policies),
```

File: lib/membrane/srtp/encryptor.ex [hunk 2]
```diff
@@ -41,10 +52,33 @@ defmodule Membrane.SRTP.Encryptor do
   end
 
   @impl true
-  def handle_demand(:output, size, :buffers, _ctx, state) do
+  def handle_event(_pad, %{handshake_data: handshake_data}, _ctx, state) do
```
Comment (mat-hek) [inline lib/membrane/srtp/encryptor.ex:55]:
```suggestion
  def handle_event(_pad, %{handshake_data: handshake_data}, _ctx, %{ready: false} = state) do
```

File: lib/membrane/srtp/encryptor.ex [hunk 3]
```diff
@@ -13,17 +13,28 @@ defmodule Membrane.SRTP.Encryptor do
...
 
   @impl true
-  def handle_init(options) do
-    {:ok, Map.from_struct(options) |> Map.merge(%{srtp: nil})}
+  def handle_init(%__MODULE__{policies: policies}) do
+    state = %{
+      policies: policies,
+      srtp: nil,
+      ready: ready?(policies),
+      buffered_demand: []
```
Comment (mat-hek) [inline lib/membrane/srtp/encryptor.ex:29]: that's not necessary, see https://hexdocs.pm/membrane_core/Membrane.Element.Action.html#t:redemand_t/0

File: lib/membrane/srtp/decryptor.ex [hunk 4]
```diff
@@ -40,14 +42,38 @@ defmodule Membrane.SRTP.Decryptor do
     {:ok, %{state | srtp: nil}}
   end
 
+  @impl true
+  def handle_event(_pad, %{handshake_data: handshake_data}, _ctx, state) do
```
Comment (mat-hek) [inline lib/membrane/srtp/decryptor.ex:46]: assert policies are empty

File: lib/membrane/srtp/decryptor.ex [hunk 5]
```diff
@@ -40,14 +42,38 @@ defmodule Membrane.SRTP.Decryptor do
...
   @impl true
   def handle_process(:input, buffer, _ctx, state) do
-    {:ok, payload} = ExLibSRTP.unprotect(state.srtp, buffer.payload)
-    {{:ok, buffer: {:output, %Buffer{buffer | payload: payload}}}, state}
+    case ExLibSRTP.unprotect(state.srtp, buffer.payload) do
+      {:ok, payload} ->
+        {{:ok, buffer: {:output, %Buffer{buffer | payload: payload}}}, state}
+
+      _ ->
+        Membrane.Logger.warn("Couldn't unprotect payload. Ignoring packet.")
```
Comment (mat-hek) [inline lib/membrane/srtp/decryptor.ex:75]:
```suggestion
      {:error, reason} ->
        Membrane.Logger.warn("""
        Couldn't unprotect payload:
        #{inspect(payload, limit: :infinity)}
        Reason: #{inspect(reason)}. Ignoring packet.
        """)
```

File: lib/membrane/rtp/session_bin.ex [hunk 6]
```diff
@@ -435,6 +466,11 @@ defmodule Membrane.RTP.SessionBin do
     Map.put(ssrcs, remote_ssrc, local_ssrc)
   end
 
+  defp get_from_register!(field, pt, state) do
+    pt_mapping = get_payload_type_mapping!(pt, state)
+    pt_mapping[field]
```
Comment (mat-hek) [inline lib/membrane/rtp/session_bin.ex:471]:
```suggestion
    Map.fetch!(pt_mapping, field)
```

File: lib/membrane/rtp/session_bin.ex [hunk 7]
```diff
@@ -108,7 +106,26 @@ defmodule Membrane.RTP.SessionBin do
...
+    options: [
+      encoding: [
+        spec: RTP.encoding_name_t() | nil,
+        default: nil,
+        description: """
+        Encoding name determining depayloader which will be used to produce output stream from RTP stream.
+        """
+      ],
+      clock_rate: [
+        spec: integer(),
```
Comment (mat-hek) [inline lib/membrane/rtp/session_bin.ex:122]:
```suggestion
        spec: integer() | nil,
```

File: lib/membrane/rtp/session_bin.ex [hunk 8]
```diff
@@ -108,7 +106,26 @@ defmodule Membrane.RTP.SessionBin do
...
+        default: nil,
+        description: """
+        Clock rate to use.
```
Comment (mat-hek) [inline lib/membrane/rtp/session_bin.ex:125]: Mention the defaults

File: lib/membrane/rtp/session_bin.ex [hunk 9]
```diff
@@ -33,8 +33,6 @@ defmodule Membrane.RTP.SessionBin do
   alias Membrane.{RTCP, RTP, SRTCP, SRTP}
   alias Membrane.RTP.{PayloadFormat, Session}
 
-  @type new_stream_notification_t :: {:new_rtp_stream, RTP.ssrc_t(), RTP.encoding_name_t()}
```
Comment (mat-hek) [inline lib/membrane/rtp/session_bin.ex:36]: I'd keep internal elements' API behind the bin's API
```
@type new_stream_notification_t :: Membrane.RTP.SSRCRouter.new_stream_notification_t()
```

**Review by mat-hek — CHANGES_REQUESTED** [review]

File: lib/membrane/srtp/decryptor.ex (hunk 4 above)
Comment (mickel8) [reply lib/membrane/srtp/decryptor.ex:46]: I left policies insted of policy because SRTCP uses Encryptor with policies so I am not sure if we want to assert here that they are empty. Do we?

File: lib/membrane/srtp/encryptor.ex [hunk 10]
```diff
@@ -41,10 +48,33 @@ defmodule Membrane.SRTP.Encryptor do
...
+  end
+
+  @impl true
+  def handle_demand(:output, size, :buffers, _ctx, %{ready: true} = state) do
     {{:ok, demand: {:input, size}}, state}
   end
 
+  @impl true
+  def handle_demand(:output, size, :buffers, _ctx, %{ready: false} = state) do
+    {:ok, Map.put(state, :buffered_demand, demand: {:input, size})}
```
Comment (mat-hek) [inline lib/membrane/srtp/encryptor.ex:75]:
```suggestion
  def handle_demand(:output, _size, :buffers, _ctx, %{ready: false} = state) do
    {:ok, state}
```

**Review by mat-hek — APPROVED** [review]

**Review by mat-hek — APPROVED** [review]
